### ISSUE TITLE
Blog (medium)

### ISSUE THREAD

**Issue by luvi01** [BlockchainInsper/site#4]

**Comment by lucasmuchaluat** [comment]
Aba de Blog que OU:
1- abre a nossa Página do Medium no nosso site (sem redirecionar)
2- pega as postagens do Medium e cria nosso próprio blog, tipo https://www.consultingclub.com.br/blog ou https://acestartups.com.br/conteudo/?utm_source=gfs&utm_campaign=gfs_ace&utm_medium=gfs
